apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: ecommerce-frontend
        image: djtoler/dp9frontend
        ports:
        - containerPort: 3000