apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: ecommerce-backend
        image: djtoler/dp9backend
        ports:
        - containerPort: 8000
